`timescale 1ns / 1ps
module VGA(
   input wire clk_25m, 
   input wire clk_100m, 
   input wire rst,
   input wire [31:0] pc,
   input wire [31:0] inst,
   input wire [31:0] alu_res,
   input wire mem_wen,
   input wire [31:0] dmem_o_data,
   input wire [31:0] dmem_i_data,
   input wire [31:0] dmem_addr,
   output wire hs, 
   output wire vs, 
   output wire [3:0] vga_r,
   output wire [3:0] vga_g,
   output wire [3:0] vga_b,
    // added for debug
   input [4:0] rs1,
   input [31:0] rs1_val,
   input [4:0] rs2,
   input [31:0] rs2_val,
   input [4:0] rd,
   input [31:0] reg_i_data,
   input reg_wen,
   input is_imm,
   input is_auipc,
   input is_lui,
   input [31:0] imm,
   input [31:0] a_val,
   input [31:0] b_val,
   input [3:0] alu_ctrl,
   input [2:0] cmp_ctrl,
   input cmp_res,
   input is_branch,
   input is_jal,
   input is_jalr,
   input do_branch,
   input [31:0] pc_branch,
   input mem_ren,
   input csr_wen,
   input [11:0] csr_ind,
   input [1:0] csr_ctrl,
   input [31:0] csr_r_data,
   input [31:0] x0,
   input [31:0] x1,
   input [31:0] x2,
   input [31:0] x3,
   input [31:0] x4,
   input [31:0] x5,
   input [31:0] x6,
   input [31:0] x7,
   input [31:0] x8,
   input [31:0] x9,
   input [31:0] x10,
   input [31:0] x11,
   input [31:0] x12,
   input [31:0] x13,
   input [31:0] x14,
   input [31:0] x15,
   input [31:0] x16,
   input [31:0] x17,
   input [31:0] x18,
   input [31:0] x19,
   input [31:0] x20,
   input [31:0] x21,
   input [31:0] x22,
   input [31:0] x23,
   input [31:0] x24,
   input [31:0] x25,
   input [31:0] x26,
   input [31:0] x27,
   input [31:0] x28,
   input [31:0] x29,
   input [31:0] x30,
   input [31:0] x31,
   input [31:0] mstatus_o,
   input [31:0] mcause_o,
   input [31:0] mepc_o,
   input [31:0] mtval_o,
   input [31:0] mtvec_o,
   input [31:0] mie_o,
   input [31:0] mip_o
   );
   wire [9:0] vga_x;
   wire [8:0] vga_y;
   wire video_on;
   VgaController vga_controller(
      .clk          (clk_25m      ),
      .rst          (rst          ),
      .vga_x        (vga_x        ),
      .vga_y        (vga_y        ),
      .hs           (hs           ),
      .vs           (vs           ),
      .video_on     (video_on     )
      );
   wire display_wen;
   wire [11:0] display_w_addr;
   wire [7:0] display_w_data;
   VgaDisplay vga_display(
      .clk          (clk_100m),  
      .video_on     (video_on),
      .vga_x        (vga_x),
      .vga_y        (vga_y),
      .vga_r        (vga_r),
      .vga_g        (vga_g),
      .vga_b        (vga_b),
      .wen          (display_wen   ),
      .w_addr       (display_w_addr),
      .w_data       (display_w_data)
   );
   VgaDebugger vga_debugger(
      .clk           (clk_100m      ), 
      .display_wen   (display_wen   ),
      .display_w_addr(display_w_addr),
      .display_w_data(display_w_data),
      .pc            (pc             ),
      .inst          (inst           ),
      .rs1           (rs1               ),
      .rs1_val       (rs1_val           ),
      .rs2(rs2),
      .rs2_val(rs2_val),
      .rd(rd),
      .reg_i_data(reg_i_data),
      .reg_wen(reg_wen),
      .is_imm(is_imm),
      .is_auipc(is_auipc),
      .is_lui(is_lui),
      .imm(imm),
      .a_val(a_val),
      .b_val(b_val),
      .alu_ctrl(alu_ctrl),
      .cmp_ctrl(cmp_ctrl),
      .alu_res(alu_res),
      .cmp_res(cmp_res),
      .is_branch(is_branch),
      .is_jal(is_jal),
      .is_jalr(is_jalr),
      .do_branch(do_branch),
      .pc_branch(pc_branch),
      .mem_wen(mem_wen),
      .mem_ren(mem_ren),
      .dmem_o_data(dmem_o_data),
      .dmem_i_data(dmem_i_data),
      .dmem_addr(dmem_addr),
      .csr_wen(csr_wen),
      .csr_ind(csr_ind),
      .csr_ctrl(csr_ctrl),
      .csr_r_data(csr_r_data),
      .x0(x0),
      .ra(x1),
      .sp(x2),
      .gp(x3),
      .tp(x4),
      .t0(x5),
      .t1(x6),
      .t2(x7),
      .s0(x8),
      .s1(x9),
      .a0(x10),
      .a1(x11),
      .a2(x12),
      .a3(x13),
      .a4(x14),
      .a5(x15),
      .a6(x16),
      .a7(x17),
      .s2(x18),
      .s3(x19),
      .s4(x20),
      .s5(x21),
      .s6(x22),
      .s7(x23),
      .s8(x24),
      .s9(x25),
      .s10(x26),
      .s11(x27),
      .t3(x28),
      .t4(x29),
      .t5(x30),
      .t6(x31),
      .mstatus_o(mstatus_o),
      .mcause_o(mcause_o),
      .mepc_o(mepc_o),
      .mtval_o(mtval_o),
      .mtvec_o(mtvec_o),
      .mie_o(mie_o),
      .mip_o(mip_o)
   );
endmodule
