# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ComputerOrnazation/lab4_3/CSSET/CPU_test.srcs/sources_1/ip/RAM_B_0/RAM_B_0.xci
# IP: The module: 'RAM_B_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ComputerOrnazation/lab4_3/CSSET/CPU_test.srcs/sources_1/ip/RAM_B_0/RAM_B_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_B_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/ComputerOrnazation/lab4_3/CSSET/CPU_test.srcs/sources_1/ip/RAM_B_0/RAM_B_0.xci
# IP: The module: 'RAM_B_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ComputerOrnazation/lab4_3/CSSET/CPU_test.srcs/sources_1/ip/RAM_B_0/RAM_B_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_B_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
