# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ROM_D_0/ROM_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_D_0 || ORIG_REF_NAME==ROM_D_0} -quiet] -quiet

# XDC: ip/ROM_D_0/ROM_D_0_ooc.xdc
