# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp01-muxctrl/muxctrl.xdc

# Block Designs: bd/OExp01_muxctrl/OExp01_muxctrl.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl || ORIG_REF_NAME==OExp01_muxctrl} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_MUX2T1_5_0_0/OExp01_muxctrl_MUX2T1_5_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_MUX2T1_5_0_0 || ORIG_REF_NAME==OExp01_muxctrl_MUX2T1_5_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_MUX2T1_5_1_0/OExp01_muxctrl_MUX2T1_5_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_MUX2T1_5_1_0 || ORIG_REF_NAME==OExp01_muxctrl_MUX2T1_5_1_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_MUX4T1_5_1_0/OExp01_muxctrl_MUX4T1_5_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_MUX4T1_5_1_0 || ORIG_REF_NAME==OExp01_muxctrl_MUX4T1_5_1_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlslice_0_0/OExp01_muxctrl_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlslice_0_0 || ORIG_REF_NAME==OExp01_muxctrl_xlslice_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlslice_0_1/OExp01_muxctrl_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlslice_0_1 || ORIG_REF_NAME==OExp01_muxctrl_xlslice_0_1} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconcat_0_0/OExp01_muxctrl_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconcat_0_0 || ORIG_REF_NAME==OExp01_muxctrl_xlconcat_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconcat_0_1/OExp01_muxctrl_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconcat_0_1 || ORIG_REF_NAME==OExp01_muxctrl_xlconcat_0_1} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconstant_0_0/OExp01_muxctrl_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconstant_0_0 || ORIG_REF_NAME==OExp01_muxctrl_xlconstant_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconstant_0_1/OExp01_muxctrl_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconstant_0_1 || ORIG_REF_NAME==OExp01_muxctrl_xlconstant_0_1} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconstant_0_2/OExp01_muxctrl_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconstant_0_2 || ORIG_REF_NAME==OExp01_muxctrl_xlconstant_0_2} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlconstant_0_3/OExp01_muxctrl_xlconstant_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlconstant_0_3 || ORIG_REF_NAME==OExp01_muxctrl_xlconstant_0_3} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_MUX8T1_8_0_0/OExp01_muxctrl_MUX8T1_8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_MUX8T1_8_0_0 || ORIG_REF_NAME==OExp01_muxctrl_MUX8T1_8_0_0} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlslice_0_2/OExp01_muxctrl_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlslice_0_2 || ORIG_REF_NAME==OExp01_muxctrl_xlslice_0_2} -quiet] -quiet

# IP: bd/OExp01_muxctrl/ip/OExp01_muxctrl_xlslice_2_0/OExp01_muxctrl_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==OExp01_muxctrl_xlslice_2_0 || ORIG_REF_NAME==OExp01_muxctrl_xlslice_2_0} -quiet] -quiet

# XDC: e:/ComputerOrnazation/lab0/OExp01-muxctrl/OExp01-muxctrl.gen/sources_1/bd/OExp01_muxctrl/OExp01_muxctrl_ooc.xdc
