#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : SCPU_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Mar 20 11:48:34 +0800 2023
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: SCPU_1.sh [-help]
# usage: SCPU_1.sh [-lib_map_path]
# usage: SCPU_1.sh [-noclean_files]
# usage: SCPU_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'SCPU_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm xil_defaultlib)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "SCPU_1.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog \
    "E:/xlinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "E:/xlinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/SCPU_ctrl_1/lab403.srcs/sources_1/new/SCPU_ctrl.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/SCPU_ctrl_1/sim/SCPU_ctrl_1.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/MUX2T1_32_0/MUX2T1_32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/MUX2T1_32_0/sim/MUX2T1_32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/MUX4T1_32_0/MUX4T1_32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/MUX4T1_32_0/sim/MUX4T1_32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/Regs_1/sources_1/new/regs.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/Regs_1/sim/Regs_1.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/or_bit_32_0/or_bit_32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/or_bit_32_0/sim/or_bit_32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/MUX8T1_32_0/MUX8T1_32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/MUX8T1_32_0/sim/MUX8T1_32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/SignalExt_32_0/SignalExt_32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/SignalExt_32_0/sim/SignalExt_32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/ADC32_0/ADC_32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/ADC32_0/sim/ADC32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/srl32_0_1/srl32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/srl32_0_1/sim/srl32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/nor32_0/nor32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/nor32_0/sim/nor32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/xor32_0/xor32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/xor32_0/sim/xor32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/or32_0/or32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/or32_0/sim/or32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/and32_0/and32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/ip/and32_0/sim/and32_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sources_1/new/ALU.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/ip/ALU_0_1/sim/ALU_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_1/lab4_1.srcs/sources_1/new/ImmGen.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_1/lab4_1.srcs/sources_1/new/REG32.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/lab4_2/lab4_2.srcs/sources_1/new/DataPath.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/ip/DataPath_0_5/sim/DataPath_0.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/new/SCPU.v" \
    "$ref_dir/../../../../CPU_test.srcs/sources_1/ip/SCPU_1_2/sim/SCPU_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.SCPU_1 xil_defaultlib.glbl -o SCPU_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./SCPU_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./SCPU_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key SCPU_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc SCPU_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./SCPU_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: SCPU_1.sh [-help]\n\
Usage: SCPU_1.sh [-lib_map_path]\n\
Usage: SCPU_1.sh [-reset_run]\n\
Usage: SCPU_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
